# Generated by Django 3.1 on 2020-08-07 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('corona', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaoPauloData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('cases', models.PositiveIntegerField(default=0, verbose_name='cases')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='deaths')),
            ],
        ),
        migrations.CreateModel(
            name='SudesteData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name='date')),
                ('cases', models.PositiveIntegerField(default=0, verbose_name='cases')),
                ('deaths', models.PositiveIntegerField(default=0, verbose_name='deaths')),
            ],
        ),
        migrations.AlterField(
            model_name='brazildata',
            name='date',
            field=models.DateField(verbose_name='date'),
        ),
    ]
